# Monorepo configuration for Nixpacks

[[apps]]
name = "backend"
path = "backend"
start = "uvicorn main:app --host 0.0.0.0 --port $PORT"

[[apps]]
name = "frontend"
path = "frontend"
start = "serve -s build --listen $PORT"
